/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import kotlin.math.sqrt

fun main() {
    val a = 5
    val b = 3
    val c = 8

    // aseguramos que 'a' no sea 0
    if (a == 0) {
        println("a no puede ser 0 en una función cuadrática.")
        return
    }

    // print a la ecuación cuadrática
    val mostrarFuncion = buildString {
        append("${a}x²")
        append(if (b >= 0) " + ${b}x" else " - ${-b}x")
        append(if (c >= 0) " + $c" else " - ${-c}")
    }
    println("Paso 1: ")
    println("La función cuadrática es: f(x) = $mostrarFuncion")

     // mostrar tabla de valores de la función en el rango de -5 a 5
   println("Paso 2: ")
   println("\nTabla de valores de f(x):")
   println(String.format("%5s %10s", "x", "f(x)"))
   for (x in -5..5) {
       val fx = calcularFuncion(a, b, c, x)
       println(String.format("%5d %10d", x, fx))
   }

  
}