/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun crearfun(){
    val a = 3
    val b = 7
    val c = 4
    val funcion = { x: Int -> a*x*x + b*x + c }
    println(funcion)
}
fun creartabla(){

}
fun main() {
    val a = 8
    val b = 3
    val c = 10
    if (a == 0){
        println("la variable no puede ser 0")
    return 
    }
    println("${a}x² + ${b}x + ${c}")
    

}
